CREATE TABLE IF NOT EXISTS clientes (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	nombre TEXT NOT NULL,
	email TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS compras (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	cliente_id INTEGER NOT NULL,
	producto TEXT NOT NULL,
	cantidad INTEGER NOT NULL,
	FOREIGN KEY (cliente_id) REFERENCES clientes(id)
);

